### ISSUE TITLE
findAndRegisterModules overwrites customized modules

### ISSUE THREAD

**Issue by steghio** [FasterXML/jackson-modules-java8#122]
Hi all,

documentation says:

````
WARNING - As of Jackson 2.x, auto-registration will only register older JSR310Module, and not newer JavaTimeModule -- this is due to backwards compatibility. Because of this make sure to either use explicit registration, or, if you want to use JavaTimeModule but also auto-registration, make sure to register JavaTimeModule BEFORE calling mapper.findAndRegisterModules()).
````

But it should be noted that, at least in version 2.9.0, invoking _mapper.findAndRegisterModules()_ will overwrite a customized module definition!

For example consider following case. Using Elasticsearch 6.5.3 with Spring Boot 2.1.6 create an entity with a field defined as:

````
@Field(type = FieldType.Date)
@JsonFormat(shape = JsonFormat.Shape.NUMBER_INT)
private LocalDateTime created;
````

Then push a value into it, for example:

````
"created" : 1563448935000
````

Now create a custom LocalDateTime deserializer that understands both Long and String:

````
public class MillisOrLocalDateTimeDeserializer extends LocalDateTimeDeserializer {

    public MillisOrLocalDateTimeDeserializer() {
        super(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
    }

    @Override
    public LocalDateTime deserialize(JsonParser parser, DeserializationContext context) throws IOException {
        if (parser.hasToken(JsonToken.VALUE_NUMBER_INT)) {
            long value = parser.getValueAsLong();
            Instant instant = Instant.ofEpochMilli(value);

            return LocalDateTime.ofInstant(instant, ZoneOffset.UTC);
        }

        return super.deserialize(parser, context);
    }

}
````

And use it in a custom EntityMapper registering the customized module BEFORE calling _findAndRegisterModules_:

````
public class CustomEntityMapper implements EntityMapper {

    private final ObjectMapper objectMapper;

    public CustomEntityMapper() {

            //needed so we can deserialize long as dates
            JavaTimeModule javaTimeModule = new JavaTimeModule();
            javaTimeModule.addDeserializer(LocalDateTime.class, new MillisOrLocalDateTimeDeserializer());

            //we use this so that Elasticsearch understands LocalDate and LocalDateTime objects
            objectMapper = new ObjectMapper()
                                      .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                                      .enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
                                     .enable(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS)
                                      .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            //MUST be registered BEFORE calling findAndRegisterModules
                                      .registerModule(javaTimeModule)
            ;

            //only autodetect fields and ignore getters and setters for nonexistent fields when serializing/deserializing
            objectMapper.setVisibility(objectMapper.getSerializationConfig().getDefaultVisibilityChecker()
                            .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
                            .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
                            .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
                            .withCreatorVisibility(JsonAutoDetect.Visibility.NONE));
            //load the other available modules as well
            objectMapper.findAndRegisterModules();
    }

    @Override
    public String mapToString(Object object) throws IOException {
        return objectMapper.writeValueAsString(object);
    }

    @Override
    public <T> T mapToObject(String source, Class<T> clazz) throws IOException {
        return objectMapper.readValue(source, clazz);
    }
}
````

Finally use the CustomEntityMapper in our Elasticsearch configuration:

````
@Configuration
@EnableElasticsearchRepositories(basePackages = "com.example.mymodel")
public class ElasticsearchConfig {

    private static final Logger LOGGER = LoggerFactory.getLogger(ElasticsearchConfig.class);

    @Value("${elasticsearch.host}")
    private String host;

    @Value("${elasticsearch.port}")
    private int port;

    @Bean(destroyMethod = "close")
    public RestHighLevelClient client() {

        LOGGER.trace("host: {}, port: {}", this.host, this.port);

        final RestHighLevelClient client = new RestHighLevelClient(RestClient.builder(new HttpHost(host, port, "http")));
        return client;
    }

    @Bean
    public ElasticsearchOperations elasticsearchTemplate() {
        return new ElasticsearchRestTemplate(client(), new CustomEntityMapper());
    }

}
````

When trying do read that field and deserialize it as LocalDateTime, Jackson will NOT invoke the custom deserializer and lead to a failure:

````
com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (VALUE_NUMBER_INT), expected VALUE_STRING: Expected array or string.
````

This can be verified by debugging the application itself and noticing that the custom deserialization code is NOT invoked at all.

Removing the call to _findAndRegisterModules_ instead solves the problem.

Am I understanding it wrong or doing it wrong somehow or is this a bug?

Thanks and cheers

**Comment by cowtowncoder** [comment]
As background, let me first note that I personally never use `findAndRegisterModules()`, and think its addition was probably Bad Idea, similar to other classpath-sniffing/scanning based convenience features.
It hides complexity and allows accidental inclusion of things just due to addition of a (possibly transitive) dependency.

But with that: the way module registration works is that modules added later on will typically have precedence over ones added earlier on (in many cases module can either "insert" or "append" things, former taking precedence, and this is what most modules choose). So calling `findAndRegisterModules()` 
after other registrations is likely to take over handling (serialize / deserialize).

Note, too, that `findAndRegisterModules()` does not have mechanism for figuring out what modules may already have been registered, with one exception: if `MapperFeature.IGNORE_DUPLICATE_MODULE_REGISTRATIONS` is enabled then module ids (via `Module.getTypeId()`, defaulting to class name) are retained by mapper and duplicate registrations are avoided.

Above is describing the way things work: I do not think there is much I can do to change this behavior with 2.x, as changes would likely break some usage somewhere.

**Comment by steghio** [comment]
Hello and thanks for your reply.

From what I understand the `MapperFeature.IGNORE_DUPLICATE_MODULE_REGISTRATIONS` is enabled by default [1](https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/MapperFeature.html#IGNORE_DUPLICATE_MODULE_REGISTRATIONS) 

And registered modules are tracked by class name since `Module.getTypeId()` is simply `getClass().getName();` [2](https://github.com/FasterXML/jackson-databind/blob/2.9/src/main/java/com/fasterxml/jackson/databind/Module.java#L61)

I just added a deserializer to the JavaTimeModule, therefore it should not be overwritten because I registered it already BEFORE calling `findAndRegisterModules` as the documentation says.

Anyway I see on master that this is gone [3](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java) or at least those methods are no longer in the ObjectMapper class.

I would however ask you to update the documentation in the README for [jackson-modules-java8](https://github.com/FasterXML/jackson-modules-java8) project since it gives the impression you can register a customized module AND invoke `findAndRegisterModules` afterwards but it does not mention  this is only the case for NON customized modules.

Thanks and cheers

**Comment by GedMarc** [comment]
I understand the concerns, I would like to suggest a method that I have great success with, 

The ServiceLoader is a very stable and common (best) practice, for "downwards" injections, and has been buffed up quite a bit in JDK 9 and up (Using the FastClassLoader for usually 80% performance increases and etc, like no more need for any classpath scanning)

What we went and did on our side is force our ServiceLoaders (in this case the Module class from Jackson) to use a defining interface making it sortable based on an integer value - Using CRP to ensure type safety for us really made it completely portable across all projects, and we implemented it across the board.

https://github.com/GedMarc/GuiceInjection/blob/6951cb47c0d27372f2ab6c95461c75c0e49c08cf/src/main/java/com/jwebmp/guicedinjection/interfaces/IDefaultService.java
e.g.
```
public interface IDefaultService<J extends IDefaultService<J>>
		extends Comparable<J>, Comparator<J>
{

public class Module<J extends Module<J>> implements IDefaultService<J>
{
}
```

Overriding sort order allows for absolute control over which services should get loaded first/last/removed/and overridden.
I do believe this will solve all problems with regards to the addon-modules, especially in the case of findAndRegisterModules.

It is both JPMS, JDK9, and JDK6-8 ready.

**Comment by cowtowncoder** [comment]
Ok. Documentation is indeed confusing and should be improved.

@GedMarc interesting approach. Something to think about wrt 3.0. My main concern (if I understand approach correctly) would probably just be that set of modules is open-ended, so finding global ordering in general would not be practical. But maybe this is more about letting users (re)order modules?

Another thing to note wrt 3.0 is this: whereas in 2.x, registration happens immediately (i.e. module is called to do its configuration), in 3.0 registration only happens when `MapperBuilder.build()` is called, so:

1. All other configuration invoke via Builder is applied first,
2. Module initialization is called, in order Modules were added

Given this it would probably be possible to add further hook(s) to let module invocation order be redefined, and applying that right between (1) and (2).

**Comment by cowtowncoder** [comment]
Will close this wrt document (I updated README).  But idea regarding module registration order is interesting; might make sense to file an issue for databind.
