### ISSUE TITLE
findCreatorAnnotation and findCreatorBinding on ParameterNamesAnnotationIntrospector behave differently

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-modules-java8#16]
I'm trying to upgrade Spring Boot to Jackson 2.9.0.pr1, addressing deprecation warnings as I do so. 

In [a test](https://github.com/spring-projects/spring-boot/blob/407894e1dff1243c535d14e939b70cea9f5a5383/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfigurationTests.java#L449-L450) we call `findCreatorBinding` on `ParameterNamesAnnotationIntrospector` to verify that it's been configured correctly. When the `Annotated` that is passed in has no creator annotation, the introspector's binding is returned. If, as recommended, I change to calling `findCreatorAnnotation` then `null` is returned instead.

The difference in behaviour between the two methods was introduced in [this commit](https://github.com/FasterXML/jackson-modules-java8/commit/c7e62df901aabf64e740aefe30acd0fe5a739607) but I can't tell if it was intentional and we should change our test, or if it wasn't and a change in Jackson is warranted.

**Comment by cowtowncoder** [comment]
@wilkinsona Change was intentional and resolved a test failure on Jackson side: problem was that if check for `JsonCreator.Mode.DEFAULT` was not made, intended override was not applied.
Override itself is of questionable value in my opinion, but since it still exists behavior should work as it did in 2.8.

Having said that... I think `ParameterNamesAnnotationIntrospector` should actually check there is an override; so I will add a tweak and see if it works closer to your expectation now.

**Comment by wilkinsona** [comment]
Thanks, @cowtowncoder. That doesn't fix the behaviour difference which we were seeing, but I can see now that it would require returning `creatorBinding` rather than `null` from `findCreatorAnnotation` when there's no `@JsonCreator` annotation. Doing so breaks one of the tests in `DelegatingCreatorTest`.

I can take a different approach in our test to verify the configuration of the module. Thanks again for the help.

**Comment by cowtowncoder** [comment]
@wilkinsona Ok thank you for verifying this. Changes like this are bit tricky to handle in backwards compatible way and I appreciate help esp. before getting release out.
