### ISSUE TITLE
JAX-RS Client using JavaTimeModule: InaccessibleObjectException: Unable to make private com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer() accessible: module com.fasterxml.jackson.datatype.jsr310 does not "opens com.fasterxml.jackson.datatype.jsr310.deser" to module com.fasterxml.jackson.databind

### ISSUE THREAD

**Issue by mwnorman** [FasterXML/jackson-modules-java8#183]
From Eclipse's (internal) JUnit5 runner. Needs additional JVM args following to work:
--add-opens com.fasterxml.jackson.datatype.jsr310/com.fasterxml.jackson.datatype.jsr310.deser=com.fasterxml.jackson.databind

When run using Maven (Surefire), it works.

Eclipse IDE version 2020-06 (also checked RC1 for upcoming Eclipse  IDE 2020-09)

**Comment by cowtowncoder** [comment]
Unfortunately I don't know why "opens" would be needed over basic "exports" (which is done for that package by `jackson-datatype-jsr310`). Does JAX-RS Client add some handling of its own over Jackson databind/module?

@GedMarc any ideas?

**Comment by mwnorman** [comment]
I solved things by simplifying my module-info.java:

open module com.algonquincollege.cst8277.restdemo {
    requires org.slf4j;
    requires info.picocli;
    // Jakarta EE 8
    requires java.ws.rs;
    requires java.servlet;
    requires com.fasterxml.jackson.jaxrs.base;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.datatype.jsr310;
}

becomes:

open module com.algonquincollege.cst8277.restdemo {
    requires org.slf4j;
    requires info.picocli;
    // Jakarta EE 8
    requires java.ws.rs;
    requires java.servlet;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.datatype.jsr310;
}

and removing the explicit use of the @JsonDeserialize(using = LocalDateTimeDeserializer.class)
annotation on the LocalDateTime field in my 'MessageHolder' class

So perhaps it has something to do with Annotation processing ...

**Comment by GedMarc** [comment]
Hmm, it's not the annotation processing, but then something definitely isn't right,
I figured it was just me, but i ended up not using jsr310 at all, and always had to annotate my fields manually with the serializer and deserializer 

What I ended up doing was taking the entire suite of time serializers, created a custom simple module and registered them there (this worked for me because i wanted a custom serializer for boolean in jdk14 with primitive types anyway)

that broke swagger because it relies on jsr310 - spent about another 2 weeks before i shaded swagger and the jsr310 dependency out...

**Comment by GedMarc** [comment]
annotations are public so it's not the open clause either, won't do anything for this one

**Comment by cowtowncoder** [comment]
I am guessing that when using (de)serializers using annotation Jackson will try to force access to constructor needed.
This should be controlled by `MapperFeature.OVERRIDE_PUBLIC_ACCESS_MODIFIERS` (and generally `MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS`).
It (calling `setAccess()` for already public constructor) could probably be prevented int this particular case since construction of (de)serializers should not be in performance-sensitive path, unlike that of constructing values deserialized.

I recommend against using `@JsonDeserialize(using = LocalDateTimeDeserializer.class)` as general practice as while this works it is not the expected usage pattern; the preferred way is to use a module (preferably jsr310-provided one, but custom will do too): this can apply other configuration settings that annotation approach might not do.
