### ISSUE TITLE
DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS not respected 

### ISSUE THREAD

**Issue by JPMoresmau** [FasterXML/jackson-modules-java8#21]
the following JSON
```
{"zdt":["2017-03-22T14:50:08.121+01:00"]}
```
Cannot be deserialized into the following class:
```
public static class TestJava8TimeBean{
		private ZonedDateTime zdt=ZonedDateTime.now();
		
		public TestJava8TimeBean(){
			
			
		}
		
		public ZonedDateTime getZdt() {
			return zdt;
		}
		
		public void setZdt(ZonedDateTime zdt) {
			this.zdt = zdt;
		}
``` 
But the mapper I use defines:
```
mapper.configure(DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS, true);
```
So using an array with one value should work. It does with strings. Also probably if DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT is enabled, an empty array should result in a null value.

**Comment by cowtowncoder** [comment]
@JPMoresmau There is no general way for `jackson-databind` to add support (since it does not know what shapes datatype might support), so every deserializer has to support these features. So there are probably plenty of datatypes that have incomplete support for this feature as well as related (empty String / empty Array to null).

I assume this is with 2.8.7.
