### ISSUE TITLE
Inconsistent deserialization of empty/missing fields in JSON to Optional

### ISSUE THREAD

**Issue by proshin-roman** [FasterXML/jackson-modules-java8#229]
I was looking around for a way how to differentiate between a field with null value and a missing field by having only the final Java object. And my assumption was that Jackson already handles it by using Optional<?>.

Just a short example:

Assuming I have the following Java DTO
```java
class Foo {
    Optional<String> bar;
}
```
I also have two JSON input payloads:
payload 1
```json
{
    "bar": null
}
```
and payload 2 (empty JSON object)
```json
{
}
```
then I would expect the following behavior of the deserialization process:
- payload 1 is deserialized into an instance of `Foo` class with `bar` equal to an empty `Optional` (`Optional.empty()`);
- payload 2 is deserialized into an instance of `Foo` class with `bar` equal to `null`.

In that way I could easily differentiate between cases when the input field was presented but equal to `null` and when the input input field was missing. Then I can implement my business logic accordingly. It might be especially important for implementing PATCH methods in CRUD APIs (no field - no changes; field is null - update the value).

But now I see that the logic is different: Optional is set to empty() in both cases mentioned above. As I can see, it all goes to this method com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer#getNullValue that always wraps the null value into an instance of Optional. In my opinion it's a bug, as it lowers the flexibility of the mapping.

What do you think, guys? Maybe there is a workaround for my problem? If so, I will appreciate any link or idea.

PS: initially the issue was reported in https://github.com/FasterXML/jackson-modules-java8/issues/154#issuecomment-938851160

**Comment by hjohn** [comment]
I have to guess at what you're trying to achieve, but there is a way to distinguish between not present and `null` that Jackson offers, which can be useful for implement `PATCH` methods:

    JsonNode input = ... ;   // data which may have explicit `null`s and absent values

    SomeObject existingData = getExistingDataFromSomewhere();  // data representing current state

    ObjectReader readerForUpdating = objectMapper.readerForUpdating(existingData);
   
    SomeObject mergedData = readerForUpdating.readValue(input);

The above `mergedData` will contain values and explicit `null`s from the input but will leave absent values to their current value. Maybe this can be useful?

**Comment by cowtowncoder** [comment]
Another thing to consider is this: currently Jackson can only detect and handle missing property values when processing "creator methods" (constructors and factory methods) -- this is the only case when existence is tracked. For setters and fields there simply is no call and no processing occurs.

So any logic for basic databinding (not including case where intermediate `JsonNode` is used, in which one can of course do whatever) one typically wants to use Constructor to pass values if "absent" value handling is needed.

Now: to coerce missing `Optional` into "empty", there are 2 ways to go about:

1. Custom deserializer
2. Use null coercion, either via `@JsonSetter(nulls = ...)` (or `contentNulls`), or equivalent mapper config (see f.ex `src/test/java/com/fasterxml/jackson/databind/deser/filter/NullConversionsPojoTest.java`)
3. Actually initialize `Optional` field and do NOT use Creator method: missing value will simply not change defaults at all

For (2) what you'd want, make `Optional.class` have coercion from `null` to `AS_EMPTY`. Not sure if there's a test to verify this works; it should but I think it may require `JsonDeserializer` to explicitly support some aspects.

**Comment by rkeytacked** [comment]
@proshin-roman like @cowtowncoder mentioned in point (3): just do not Creator method.

My complete example for exactly your use case works really well up to date. Lombok adds an empty constructor plus getters/setters via `@Data`:

```java
import java.util.Optional;
import lombok.Data;

@Data
public class Foo {
  private Optional<Long> bar;
  private Optional<String> foobar;
}
```

I even added unit tests in my project to ensure that missing fields stay `null`, and existing fields with `null` JSON value become `Optional.EMPTY`.

**Comment by proshin-roman** [comment]
thank you, @cowtowncoder, @rkeytacked and @hjohn for your answers - I will try solutions you proposed and either close the ticket or leave another comment 👍

**Comment by dulshand** [comment]
> [@proshin-roman](https://github.com/proshin-roman): like [@cowtowncoder](https://github.com/cowtowncoder) mentioned in point (3)
> 
> * just do not use the Creator method.
> 
> My complete example for exactly your use case works really well up to date. Lombok adds an empty constructor plus getters/setters via `@Data`:
> 
> import java.util.Optional;
> import lombok.Data;
> 
> @Data
> public class Foo {
>   private Optional<Long> bar;
>   private Optional<String> foobar;
> }
> I even added unit tests in my project to ensure that missing fields stay `null`, and existing fields with `null` JSON value become `Optional.EMPTY`.
> 
> {
>   "foobar" : null
> }
> turns into => `Foo(bar=null, foobar=Optional.EMPTY)`

I have been using this approach for quite a some time with Spring Boot versions 3.x. Recently we upgraded to Spring boot 4.0.5 which uses Jackson 3.x. In Jackson 3.x they changed the deserialization of Optional to so that missing optional attributes will also be assigned with Optional.EMPTY. That broke the tristate assumption of our code. The only way to to work around was to use 

spring:
   jackson:   
    use-jackson2-defaults: true

This is a temporary workaround because jackson2 may not be around after some time. 
I tried to register a custom deserializer vial object mapper and many other ways. But Spring boot 4.0 seems to adamantly use its own internal Object Mapper in Smart converters to do data binding which does not support Tristate behavior with Optionals. Some suggested using a custom type called TriState which is similar to optional but it internally codes using generics, the tristate behavior in data binding. That is a long shot because if you have a lot of Patch requests, you will have to change a lot of code. Has someone already developed a better solution to this with Jackson 3.x?

**Comment by veda-tschoening** [comment]
> Has someone already developed a better solution to this with Jackson 3.x?

In my opinion, a custom some sort of TriState is the best approach, because that can always be non-null, can have it's own helper to handle the different cases of MISSING vs. NULL etc. It works pretty well with custom de-/serialization. We've rolled our own class and are pretty happy with it so far.
