### ISSUE TITLE
Optional object Serialization Whole Object required instead of value.

### ISSUE THREAD

**Issue by prakharporwal** [FasterXML/jackson-modules-java8#261]
- Json Serialization for a Optional value just has value object.
- I want the whole Optional object to be serialized. Is there a way I can enable that using this module.

What I want

```json
{
    "present": true,
     "value": {
            "id": 8
      }
}
```

What I get right now
```json
{
   "id":  8
}
```

**Comment by cowtowncoder** [comment]
@prakharporwal There is no way to serialize `Optional` "as POJO" right now; in theory `@JsonFormat(shape = JsonFormat.Shape.OBJECT)` might work , and that would provide `present` but since "value" is accessed with `get()` (and not `getValue()`) that would not be serialized even then. It'd have to be applied either via "config overrides" system (for global setting) or annotation on `Optional<x>` valued property.

... theoretically, of course, mix-in annotation could be added on `get()`, but I don't know if combination actually would work (depends on individual serializer implementation).

More likely though you can make this work with custom serializer. One challenge there may be is handling of generic types -- if you need to find value type, cannot use `SimpleModule`s `addSerializer()` methods, but need to implement `Serializers` provider.
But it is possible you don't need to worry about that if the default serializer for value types you use work fine (are non-generic types).

**Comment by prakharporwal** [comment]
@cowtowncoder Thanks for responding. Still if I am not able to serialise just the value part of the Optional.
How do I deserialize it into an Optional value.
The Object is a nested-generic type and I want to convert the JSON to Optional.
I am using the JDK8 module and I am not sure why it is failing.

Here is Example of my case :

Currently I am using this
```java
    private final static ObjectMapper objectMapper = new ObjectMapper();
    
    objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    objectMapper.configure(DeserializationFeature.USE_JAVA_ARRAY_FOR_JSON_ARRAY, true)

    Optional<List<List<String>>> val = mapper.readValue( JSON["object"], new TypeReference<Optional<List<List<String>>>(){}.getType() );
```

```json
{
  "object": [
    [ "first","second"],
    ["third","fourth"],
  ]
}
```

I expect the `val` to have the value properly deserialized. Am I doing something wrong here ?

**Comment by cowtowncoder** [comment]
What does `JSON["object"]` here refer to? What is the actual JSON content being read?

Also: you are not registering module for `Optional` support in your example so that would prevent it from working.

**Comment by prakharporwal** [comment]
> What does `JSON["object"]` here refer to? What is the actual JSON content being read?
my bad . Have updated the code in above comment.

> Also: you are not registering module for `Optional` support in your example so that would prevent it from working.
I am using the jdk8 Module . Are you talking about the same ? I register missed to mention in the code above.

**Comment by cowtowncoder** [comment]
You are welcome @prakharporwal !
