### ISSUE TITLE
(date/time) Support `jackson-datatype-Threetenbp` fork?

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-modules-java8#4]
(move from https://github.com/FasterXML/jackson-datatype-jsr310/issues/90 by @cbornet)

------

The [threetenbp](https://github.com/joschi/jackson-datatype-threetenbp) fork doesn't seem very lively and hasn't been updated since jackson 2.6.4.
Could FasterXML provide its own threetenbp implementation or maintain this one ?
I understand this is a lot of work but threetenbp is now the recommended date lib for apps that can't upgrade to JDK8 (eg. android) so it would be great to have official support.

**Comment by cbornet** [comment]
> @cbornet more the merrier and I would not be against support, but right now limitation is time. So I could definitely help, and take of releasing new versions as part of standard release process. But I would need help with transition. Do you know authors jackson-datatype-threetenbdp to contact.

AFAIK the maintainer is @joschi

**Comment by cowtowncoder** [comment]
@cbornet Ah. That's lucky... he's active contributor here too. :)

**Comment by joschi** [comment]
I mainly neglected the updates of [jackson-datatype-threetenbp](https://github.com/joschi/jackson-datatype-threetenbp) for two reasons:

* It doesn't seem to have many users (4 stars on GitHub, 2,000 downloads from Maven Central)
* It's a bit cumbersome to port all jackson-datatype-jsr310 patches to the codebase (because of different package names, different imports etc.).

This being said, if there's interest in having support for ThreeTenBP in Jackson, I can invest some time updating the project.

**Comment by cbornet** [comment]
Well, it seems people are used to joda and don't know much about threetenbp so there is a bit of promotion to do. But to do that, we need to have libraries and tools for threetenbp at the same level than joda. For instance, I've made a PR in swagger-codegen to use jackson-datatype-threetenbp the default library for jackson based languages so your download count should increase hopefully :smile: 
You also now have 5 stars !

**Comment by cbornet** [comment]
Also people probably don't trust a fork too much and an official "FasterXML" module would be more popular I think.

**Comment by cowtowncoder** [comment]
I think this could be useful, but thinking about challenges I guess the biggest challenges would be keeping it in-sync with the main module. Codebase is rather big for an extension module, so ideally there would be a way that minimizes code duplication.

**Comment by joschi** [comment]
I've synced `jackson-datatype-threetenbp` with version 2.8.4 of `jackson-datatype-jsr310` (closing joschi/jackson-datatype-threetenbp#8).

I'm willing to move the project under the FasterXML umbrella, though I share @cowtowncoder's thoughts about keeping the two projects in-sync. Since the APIs of `java.time` and [ThreeTen](http://www.threeten.org/) are pretty stable nowadays, there shouldn't be too many changes to the modules, though.

**Comment by cowtowncoder** [comment]
I don't think this will happen -- while it's a useful module, it seems to be well-maintained and "just works". Not much benefit from moving here.
