### ISSUE TITLE
Add support for threeten-extra

### ISSUE THREAD

**Issue by tsachev** [FasterXML/jackson-modules-java8#41]
Hi there is a project [threeten-extra](http://www.threeten.org/threeten-extra/) by @jodastephen that 

>  provides additional date-time classes that complement those in Java SE 8.

I am interested in adding support for types defined there (especially `Interval`).
Ideally I would like this module to autodetect if three-ten is present and register serializers/deserializers.

But maybe it should live in its own separate module, WDYT?

**Comment by cowtowncoder** [comment]
@tsachev Yes, I think this would need to be a separate datatype module; especially if with Jackson 3.0 we are to embed Java 8 types all in core databind (not decided yet but possible).

It'd be interesting to see where to locate this module; lately we have tried to combine modules into multi-maven-module repos due to amount of work needed for release. But I think it makes sense to maybe first create stand-alone module and then see if it could be combined with similar others.
There are a few odds-and-ends datatype modules that could probably be combined.

So, +1 for datatype module, and I think separate one makes sense. As to auto-detection I think this may be bit orthogonal thing too -- we do little bit of that for JDK, but not for anything else.
Perhaps there could be something else (uber-project? Discovery module?) that could be built to allow auto-discovery and registration of modules -- like detecting existence of specific core class of a datatype lib, then see if matching Module (by name, or by SPI metadata?) can be located.
This sounds like something that could be useful (... or, PITA... :-) ) and maybe could be designed for Jackson 3.0, which we are starting to scope.

**Comment by cowtowncoder** [comment]
If this still makes sense, can re-file at `jackson-future-ideas`, or discuss on mailing lists.
Will close issue here as part of clean up, not because it wasn't worth doing but just that it's sort of out o scope right here.
