### ISSUE TITLE
Java8 date has no milliseconds long transform to `LocalDateTime`

### ISSUE THREAD

**Issue by ChunMengLu** [FasterXML/jackson-modules-java8#47]
Java8 date has no milliseconds long transform to date

https://github.com/FasterXML/jackson-modules-java8/blob/cee08b09f6c1f50253fc9695d3109202c35ca2f8/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/LocalDateTimeDeserializer.java#L64

`jackson-datatype-joda`

https://github.com/FasterXML/jackson-datatype-joda/blob/602994f5c8cecdf6bd88fff4705e97a8f58bd798/src/main/java/com/fasterxml/jackson/datatype/joda/deser/LocalDateTimeDeserializer.java#L43

**Comment by cowtowncoder** [comment]
Ok, digging into this, I think the reason is that there is no way to reliably figure out milliseconds-since-epoch (value returned by `System.currentTimeMillis()`, or stored in Java 8 `Instant` values) value from `LocalDateTime`. Problem being that `LocalDateTime` does not represent a specific time in itself and requires time zone for that. Javadocs say:

    It cannot represent an instant on the time-line without additional information such as an offset or time-zone.

Because of this, it would not make sense to accept raw timestamp.

What I can do is to improve error message to indicate that such value can not be deserialized using standard deserializer: if users have more application-specific limitations (such as always ensuring these values can be handled as UTC), they can register custom deserializer.

**Comment by cowtowncoder** [comment]
Improved error messages to indicate that timestamp is not allowed since there is no timezone to use.

**Comment by dmak** [comment]
If I may re-open the discussion on the issue. Maybe `LocalDateTimeDeserializer` implementation could be more flexible and allow one of two choices when handling numeric / timestamp inputs:
* Assume that timestamp is in UTC.
* Assume that timestamp is in local timezone.

I think these two will cover most of the usecases.

**Comment by cowtowncoder** [comment]
I could potentially see assumption of `UTC`, but I would be pretty set against using any definition of local timezone -- this tends to produce lots of problems when users do not realize that sender and receiver (writer and reader) must somehow agree on definition.

If so, the way I could see this working -- and if so, I think a new specific issue should be created with link to this one:

1. This module has a new configuration setting to enable this optional behavior (I can help with configurability) of accepting JSON integer number
2. If setting is not enabled, exception given would indicate existence of such option

I really do not want users to accidentally end up using what to me looks like a Bad Way of Doing Things.
I know it is quite common for "local" variants to cause confusion, and abuse is wide-spread (Avro logical types seem to suffer from this, f.ex), so I would not want to make problem worse.
At the same time if such behavior really is needed for interoperability with other frameworks questionable uses it makes sense to have opt-in feature to allow that.
