### ISSUE TITLE
NON_ABSENT not working for Optional.empty()

### ISSUE THREAD

**Issue by yassenb** [FasterXML/jackson-modules-java8#62]
I expect the below code to output `{"x":5}` but it outputs `{"x":5,"z":null}`

```java
Map<String, Object> map = new HashMap<>();
map.put("x", 5);
map.put("y", null);
map.put("z", Optional.empty());
String json = new ObjectMapper()
    .registerModule(new Jdk8Module())
    .setDefaultPropertyInclusion(Include.NON_ABSENT)
    .writeValueAsString(map);
System.out.println(json);
```

`NON_EMPTY` produces the desired output

**Comment by cowtowncoder** [comment]
Which Jackson version?

**Comment by yassenb** [comment]
2.9.5

**Comment by cowtowncoder** [comment]
I think the problem here is that values of `Map`s (and ones wrapped in `Optional` and similar) follow separate setting ("content" vs "value") inclusion. So instead of calling legacy version of `setDefaultPropertyInclusion` that takes single vlaue, you may want:

        JsonInclude.Value incl =
                JsonInclude.Value.construct(JsonInclude.Include.NON_ABSENT, JsonInclude.Include.NON_ABSENT);
       mapper.setDefaultPropertyInclusion(incl);

instead: here the first value refers to values themselves (root values, values of properties), and second value for "content" values, specifically elements of `Map`s and referential types (`Optional`, `AtomicReference`).

I'll have a look to see if this has been properly tested or not, however; it is possible there is a bug.
But I just want to rule out possibility it is due to legacy method passing `JsonInclude.Include` value that is different than expected.

**Comment by cowtowncoder** [comment]
Oh. Actually... that is not the problem here.

Problem is that due to type erasure, your value has basically type of `Map<?,?>`, which is about same as `Map<Object,Object>`. Because of this, inclusion criteria is checked for value type of `Object`, for which "absent" has no meaning.

For values to be handled properly type would need to be `Map<K, Optional<V>>` (where `K` need not be bound to anything other than `Object`; and `V` may likewise be just unbound or whatever value contained). Otherwise inclusion checks will not work.
Usually this is not a problem with `Map`-valued properties since type information is retained: but the same is not true for root values.
This is why I strongly recommend NOT using generic types as root values but instead having POJO as root value. Even if enclosing a single `Collection` or `Map`.

If you do want to use `Map` as root value you can still make things work the way you want.
Two main work-arounds are:

1. Use helper type that solves type erasure: `class MyOptMap extends HashMap<String, Optional<?>> { }` -- if so, type information can be extracted and inclusion rules will work
2. Explicitly specify type to use via `ObjectWriter`:

    ObjectWriter w = mapper.writerFor(new TypeReference<Map<String,Optional<?>>>() { });
    String json = w.writeValueAsString(map);

**Comment by yassenb** [comment]
Thank you for the quick response and the detailed explanation.
However, the proposed workarounds are not an option since the map can contain other types of objects, not only `Optional`. It does indeed work with a POJO but creating a new class for every map in our code only to aid serialization of `Optional`-s is cumbersome.
As stated, when replacing `NON_ABSENT` with `NON_EMPTY` in the above code it works as desired. So can't `NON_ABSENT` be made to work the same as `NON_EMPTY` when it comes to `Optional`?

**Comment by cowtowncoder** [comment]
If they are heterogenous, you can not achieve what you want then with this feature.
I don't see how `NON_EMPTY` would work any better.

**Comment by yassenb** [comment]
I don't want to use `NON_EMPTY`, I want to use `NON_ABSENT` because I still want to serialize empty collections. I am only giving  an example that it works with `NON_EMPTY` and `NON_ABSENT` should behave the same way for `Optional`-s

**Comment by cowtowncoder** [comment]
@yassenb That does not work, will not work. Sorry.
