### ISSUE TITLE
Add Automatic-Module-Name for JDK9 interoperability

### ISSUE THREAD

**Issue by forax** [FasterXML/jackson-modules-java8#77]
Hi,
https://github.com/FasterXML/jackson-core/issues/397 add Automatic-Module-Name to core and databind but other projects like jackson-annotations were not updated.

Stephen Colebourne has started to list all projects that have a list an Automatic-Module-Name, as you can see only core and databind have been updated
https://github.com/jodastephen/jpms-module-names/blob/master/generated/module-maven.properties#L1

I personally need jackson-annotations and  jackson-module-java8 so i will log a bug for these two modules but all modules should be updated IMO.

**Comment by cowtowncoder** [comment]
`jackson-annotations` actually got this for `2.9.1`, I think; I need to think of what to do with `jackson-bom` since ideally I would drop patch revision, but in this one specific case there is a reason for dependency to later patch version..

As to other repos; you can add issues for repos that are missing this, but I thought that parent pom actually includes instructions to generate module name.
There definitely should be module names for other repose so I am not quite sure where discrepancy comes from: it is possible I guess that information is somehow incorrect. I think I did verify just that metadata entry is added in Manifest, but Oracle's tooling for pre-Java-9 hasn't allowed much other verification.

**Comment by cowtowncoder** [comment]
Looking at jars build for 2.9.6 for, say, java8 datetime, does show:

```
Manifest-Version: 1.0
Automatic-Module-Name: com.fasterxml.jackson.datatype.jsr310
Bnd-LastModified: 1528839425523
Build-Jdk: 1.8.0_102
```

and similarly for base modules.

So to me it seems like automatic name is included.

Is Stephen's list generated from artifacts from Maven, or using some other means?

**Comment by forax** [comment]
yes,
the generator used for creating Stephen's list was not scanning Central for jackson, i've sent a pull request for that (https://github.com/jodastephen/jpms-module-names/pull/20).
